clean:
	rm -f *.out *.exe* *.o

lesson1: clean
	gcc -c -m32 lesson1.s -o lesson1.o
	gcc lesson1.o -o lesson1.exe
	gdb lesson1.exe

lesson2: clean
	gcc -m32 lesson2.s -o lesson2.exe
	gdb lesson2.exe

lesson3b: clean
	gcc -m32 lesson3b.s -o lesson3b.exe
	gdb lesson3b.exe

lesson4a-challenge: clean
	gcc -m32 lesson4a-challenge.s -o lesson4a-challenge.exe
	gdb lesson4a-challenge.exe

lesson4b: clean
	gcc -m32 lesson4b.s -o lesson4b.exe
	gdb lesson4b.exe

lesson5a-challenge: clean
	gcc -m32 lesson5a-challenge.s -o lesson5a-challenge.exe
	gdb lesson5a-challenge.exe

lesson5a: clean
	gcc -m32 lesson5a.s -o lesson5a.exe
	gdb lesson5a.exe

lesson5b: clean
	gcc -m32 lesson5b.s -o lesson5b.exe
	gdb lesson5b.exe

lesson5c-challenge: clean
	gcc -m32 lesson5c-challenge.s -o lesson5c-challenge.exe
	gdb lesson5c-challenge.exe

lesson5c: clean
	gcc -m32 lesson5c.s -o lesson5c.exe
	gdb lesson5c.exe

lesson6a-challenge: clean
	gcc -m32 lesson6a-challenge.s -o lesson6a-challenge.exe
	gdb lesson6a-challenge.exe

lesson6a: clean
	gcc -m32 lesson6a.s -o lesson6a.exe
	gdb lesson6a.exe

homework: clean
	gcc -m32 homework.s -o homework.exe
	gdb homework.exe

lista: clean
	gcc -m32 lista.s -o lista.exe
	./lista.exe
